// frontend/src/app/components/StatsCard.vue
<template>
  <div class="stats-card card mb-3" :class="{ 'bg-primary text-white': variant === 'primary' }">
    <div class="card-body">
      <div class="d-flex justify-content-between align-items-start">
        <div>
          <p class="card-text mb-1">{{ title }}</p>
          <h4 class="card-title mb-0">{{ value }}</h4>
        </div>
        <div v-if="icon" class="text-muted" style="font-size: 2rem;">
          <i :class="icon"></i>
        </div>
      </div>
      <div v-if="trend" class="mt-2">
        <small :class="trend > 0 ? 'text-success' : 'text-danger'">
          <i :class="trend > 0 ? 'bi bi-arrow-up' : 'bi bi-arrow-down'"></i>
          {{ Math.abs(trend) }}%
        </small>
      </div>
    </div>
  </div>
</template>

<script setup>
defineProps({
  title: { type: String, required: true },
  value: { type: [String, Number], required: true },
  icon: { type: String },
  trend: { type: Number },
  variant: { type: String, default: 'light' }
})
</script>

<style scoped>
.stats-card {
  border: 1px solid #dee2e6;
  border-radius: 0.375rem;
}

.stats-card.bg-primary {
  border: none;
}
</style>

// frontend-react/src/components/StatsCard.jsx
const StatsCard = ({ icon, iconBg, title, value, subtitle, trend, trendColor = 'green' }) => {
  const trendColors = {
    green: 'text-green-600 bg-green-50',
    red: 'text-red-600 bg-red-50',
    yellow: 'text-yellow-600 bg-yellow-50',
    blue: 'text-blue-600 bg-blue-50',
  };

  return (
    <div className="bg-white rounded-xl shadow-sm border border-gray-100 p-6 hover:shadow-md transition-shadow">
      <div className="flex items-start justify-between">
        <div>
          <p className="text-sm text-gray-600 font-medium mb-2">{title}</p>
          <div className="flex items-baseline gap-2">
            <h3 className="text-3xl font-bold text-gray-800">{value}</h3>
            {trend !== undefined && (
              <span className={`text-sm ${trendColors[trendColor]}`}>
                {trend > 0 ? (
                  <>
                    <i className="bi bi-arrow-up-right"></i> {trend}%
                  </>
                ) : trend < 0 ? (
                  <>
                    <i className="bi bi-arrow-down-right"></i> {Math.abs(trend)}%
                  </>
                ) : (
                  'Sin cambios'
                )}
              </span>
            )}
          </div>
          {subtitle && (
            <p className="text-xs text-gray-500 mt-2">{subtitle}</p>
          )}
        </div>
        <div className={`w-12 h-12 rounded-lg flex items-center justify-center text-xl text-white ${iconBg}`}>
          <i className={`bi ${icon}`}></i>
        </div>
      </div>
    </div>
  );
};

export default StatsCard;
