// frontend-react/src/views/empleado/MarcarAsistencia.jsx
import { useState, useEffect } from 'react'
import { useNavigate, Link } from 'react-router-dom'
import api from '../../services/api'

const MarcarAsistencia = () => {
  const navigate = useNavigate()
  const [loading, setLoading] = useState(false)
  const [mensaje, setMensaje] = useState('')
  const [tipo, setTipo] = useState('')
  const [sidebarOpen, setSidebarOpen] = useState(false)
  const [asistenciaHoy, setAsistenciaHoy] = useState(null)
  const [loadingCheck, setLoadingCheck] = useState(true)

  useEffect(() => {
    const token = localStorage.getItem('empleadoToken')
    if (!token) navigate('/empleado/login')
    checkAsistenciaHoy()
  }, [navigate])

  const checkAsistenciaHoy = async () => {
    try {
      setLoadingCheck(true)
      const response = await api.getAsistenciaHoy()
      setAsistenciaHoy(response.data)
    } catch (err) {
      console.log('No hay asistencia hoy')
      setAsistenciaHoy(null)
    } finally {
      setLoadingCheck(false)
    }
  }

  const marcarAsistencia = async () => {
    setLoading(true)
    setMensaje('')
    try {
      await api.marcarEntrada()
      setMensaje('Asistencia marcada exitosamente')
      setTipo('success')
      checkAsistenciaHoy()
    } catch (err) {
      const errorMsg = err.response?.data?.message || 'Error al marcar asistencia'
      setMensaje(errorMsg)
      setTipo('error')
    } finally { setLoading(false) }
  }

  const logout = () => {
    localStorage.removeItem('empleadoToken')
    localStorage.removeItem('empleado')
    navigate('/empleado/login')
  }

  const getEstadoBadge = () => {
    if (!asistenciaHoy) return null
    switch (asistenciaHoy.estado) {
      case 'PRESENTE': return { bg: 'bg-green-100', text: 'text-green-700', label: 'Presente' }
      case 'TARDANZA': return { bg: 'bg-yellow-100', text: 'text-yellow-700', label: 'Tardanza' }
      case 'AUSENTE': return { bg: 'bg-red-100', text: 'text-red-700', label: 'Ausente' }
      default: return null
    }
  }

  const badge = getEstadoBadge()

  const navItems = [
    { to: '/empleado/dashboard', icon: 'bi-house', label: 'Inicio' },
    { to: '/empleado/asistencia', icon: 'bi-clock', label: 'Asistencia', active: true },
    { to: '/empleado/mis-asistencias', icon: 'bi-calendar-check', label: 'Mis Asistencias' },
    { to: '/empleado/licencias', icon: 'bi-calendar', label: 'Licencias' },
    { to: '/empleado/solicitar-licencia', icon: 'bi-plus-circle', label: 'Solicitar' },
    { to: '/empleado/perfil', icon: 'bi-person', label: 'Mi Perfil' },
  ]

  return (
    <div className="flex min-h-screen bg-gray-50">
      <aside className={`fixed inset-y-0 left-0 z-50 w-64 bg-white shadow-lg transform transition-transform duration-300 ${sidebarOpen ? 'translate-x-0' : '-translate-x-full'} md:relative md:translate-x-0`}>
        <div className="p-4 border-b border-gray-100 flex items-center justify-between">
          <div className="flex items-center gap-3">
            <div className="w-10 h-10 rounded-xl flex items-center justify-center text-white bg-gradient-green"><i className="bi bi-person-badge"></i></div>
            <span className="font-semibold text-gray-800">Empleado</span>
          </div>
          <button onClick={() => setSidebarOpen(false)} className="md:hidden text-gray-500">
            <i className="bi bi-x-lg text-xl"></i>
          </button>
        </div>
        <nav className="p-4 space-y-1">
          {navItems.map((item) => (
            <Link key={item.to} to={item.to} onClick={() => setSidebarOpen(false)} className={`flex items-center gap-3 px-4 py-3 rounded-xl transition-all ${item.active ? 'text-white bg-gradient-green' : 'text-gray-600 hover:bg-gray-100'}`}>
              <i className={`bi ${item.icon}`}></i><span>{item.label}</span>
            </Link>
          ))}
        </nav>
        <div className="p-4 border-t border-gray-100">
          <button onClick={logout} className="flex items-center gap-3 px-4 py-3 rounded-xl text-red-600 hover:bg-red-50 w-full"><i className="bi bi-box-arrow-right"></i><span>Cerrar Sesión</span></button>
        </div>
      </aside>

      {sidebarOpen && <div className="fixed inset-0 bg-black/50 z-40 md:hidden" onClick={() => setSidebarOpen(false)}></div>}

      <main className="flex-1 p-4 md:p-8">
        <div className="flex items-center justify-between mb-6 md:mb-8">
          <h1 className="text-2xl md:text-3xl font-bold text-gray-800">Marcar Asistencia</h1>
          <button onClick={() => setSidebarOpen(true)} className="md:hidden text-gray-600 p-2">
            <i className="bi bi-list text-2xl"></i>
          </button>
        </div>

        {loadingCheck ? (
          <div className="flex justify-center py-12"><div className="w-10 h-10 border-4 border-green-500 border-t-transparent rounded-full animate-spin"></div></div>
        ) : asistenciaHoy ? (
          <div className="bg-white rounded-xl p-6 md:p-8 shadow-sm border border-gray-100 max-w-md mx-auto text-center">
            <div className={`w-20 h-20 md:w-24 md:h-24 mx-auto mb-4 md:mb-6 rounded-full flex items-center justify-center text-4xl md:text-5xl ${badge?.bg || 'bg-gray-100'} ${badge?.text || 'text-gray-700'}`}>
              <i className={`bi ${asistenciaHoy.hora_entrada ? 'bi-check-circle-fill' : 'bi-x-circle'}`}></i>
            </div>
            <h2 className="text-xl md:text-2xl font-bold text-gray-800 mb-2">Asistencia Registrada</h2>
            <div className={`inline-block px-4 py-2 rounded-full ${badge?.bg || 'bg-gray-100'} ${badge?.text || 'text-gray-700'} font-semibold mb-4`}>
              {badge?.label || asistenciaHoy.estado}
            </div>
            {asistenciaHoy.hora_entrada && (
              <p className="text-gray-500">Entrada: {asistenciaHoy.hora_entrada}</p>
            )}
            {asistenciaHoy.hora_salida && (
              <p className="text-gray-500">Salida: {asistenciaHoy.hora_salida}</p>
            )}
            <p className="text-gray-400 text-sm mt-4">{new Date().toLocaleDateString('es-ES', { weekday: 'long', year: 'numeric', month: 'long', day: 'numeric' })}</p>
          </div>
        ) : (
          <div className="bg-white rounded-xl p-6 md:p-8 shadow-sm border border-gray-100 max-w-md mx-auto text-center">
            <div className="w-20 h-20 md:w-24 md:h-24 mx-auto mb-4 md:mb-6 rounded-full flex items-center justify-center text-4xl md:text-5xl text-white bg-gradient-green shadow-gradient-green">
              <i className="bi bi-clock-fill"></i>
            </div>
            <h2 className="text-xl md:text-2xl font-bold text-gray-800 mb-2">Registro de Asistencia</h2>
            <p className="text-gray-500 mb-4 md:mb-6 text-sm md:text-base">{new Date().toLocaleDateString('es-ES', { weekday: 'long', year: 'numeric', month: 'long', day: 'numeric' })}</p>
            
            <button onClick={marcarAsistencia} disabled={loading}
              className="w-full py-3 md:py-4 rounded-xl text-white font-semibold text-base md:text-lg disabled:opacity-70 flex items-center justify-center gap-2 bg-gradient-green shadow-gradient-green">
              {loading ? (<><span className="w-5 h-5 border-2 border-white border-t-transparent rounded-full animate-spin"></span> Registrando...</>) : (<><i className="bi bi-check-circle"></i> Marcar Asistencia</>)}
            </button>

            {mensaje && (
              <div className={`mt-4 p-3 rounded-xl ${tipo === 'success' ? 'bg-green-100 text-green-700' : 'bg-red-100 text-red-700'}`}>
                {mensaje}
              </div>
            )}
          </div>
        )}
      </main>
    </div>
  )
}

export default MarcarAsistencia

// frontend/src/views/empleado/MarcarAsistencia.vue
<template>
  <EmpleadoLayout>
    <div class="asistencia-container">
      <h1>Marcar Asistencia</h1>

      <div class="estado-actual">
        <div class="estado-card" :class="estado.clase">
          <div class="estado-icon">
            <i :class="estado.icono"></i>
          </div>
          <div class="estado-info">
            <h3>{{ estado.titulo }}</h3>
            <p>{{ estado.hora }}</p>
          </div>
        </div>
      </div>

      <div class="botones-marcado">
        <button
          @click="marcarEntrada"
          :disabled="!puedeMarcarEntrada || loading"
          class="btn-marcado btn-entrada"
        >
          <div class="btn-icon">
            <i class="bi bi-box-arrow-in-right"></i>
          </div>
          <div class="btn-text">
            <span class="btn-title">Entrada</span>
            <span class="btn-desc">8:00 AM - 6:00 PM</span>
          </div>
          <div class="btn-check" v-if="asistenciaHoy?.hora_entrada">
            <i class="bi bi-check-circle-fill"></i>
          </div>
        </button>

        <button
          @click="marcarSalida"
          :disabled="!puedeMarcarSalida || loading"
          class="btn-marcado btn-salida"
        >
          <div class="btn-icon">
            <i class="bi bi-box-arrow-right"></i>
          </div>
          <div class="btn-text">
            <span class="btn-title">Salida</span>
            <span class="btn-desc">Hasta las 6:00 PM</span>
          </div>
          <div class="btn-check" v-if="asistenciaHoy?.hora_salida">
            <i class="bi bi-check-circle-fill"></i>
          </div>
        </button>
      </div>

      <div class="historial-reciente">
        <h3>Últimos 7 días</h3>
        <div class="historial-table">
          <table>
            <thead>
              <tr>
                <th>Fecha</th>
                <th>Entrada</th>
                <th>Salida</th>
                <th>Horas</th>
                <th>Estado</th>
              </tr>
            </thead>
            <tbody>
              <tr v-for="item in historial" :key="item.id">
                <td>{{ formatDate(item.fecha) }}</td>
                <td>{{ item.hora_entrada || '-' }}</td>
                <td>{{ item.hora_salida || '-' }}</td>
                <td>{{ calcularHoras(item) }}</td>
                <td>
                  <span class="estado-badge" :class="getEstadoClass(item)">
                    {{ getEstado(item) }}
                  </span>
                </td>
              </tr>
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </EmpleadoLayout>
</template>

<script>
import EmpleadoLayout from '../../components/empleado/EmpleadoLayout.vue'
import authEmpleado from '../../services/authEmpleado'
import { useNotification } from '../../services/notification.service'

export default {
  name: 'MarcarAsistencia',
  components: {
    EmpleadoLayout
  },
  data() {
    return {
      loading: false,
      asistenciaHoy: null,
      historial: []
    }
  },
  computed: {
    puedeMarcarEntrada() {
      return !this.asistenciaHoy?.hora_entrada
    },
    puedeMarcarSalida() {
      return this.asistenciaHoy?.hora_entrada && !this.asistenciaHoy?.hora_salida
    },
    estado() {
      if (!this.asistenciaHoy) {
        return {
          titulo: 'Sin registrar',
          hora: 'Marca tu entrada para comenzar el día',
          icono: 'bi bi-clock-history',
          clase: 'pending'
        }
      }
      if (this.asistenciaHoy.hora_entrada && !this.asistenciaHoy.hora_salida) {
        return {
          titulo: 'En progreso',
          hora: `Entrada registrada a las ${this.asistenciaHoy.hora_entrada}`,
          icono: 'bi bi-play-circle-fill',
          clase: 'in-progress'
        }
      }
      return {
        titulo: 'Día completado',
        hora: `${this.asistenciaHoy.hora_entrada} - ${this.asistenciaHoy.hora_salida}`,
        icono: 'bi bi-check-circle-fill',
        clase: 'completed'
      }
    }
  },
  async mounted() {
    await this.cargarDatos()
  },
  methods: {
    async cargarDatos() {
      this.loading = true
      try {
        const [hoy, historial] = await Promise.all([
          authEmpleado.getAsistenciaHoy().catch(() => ({ data: null })),
          authEmpleado.getHistorialAsistencia({ limit: 7 }).catch(() => ({ data: [] }))
        ])
        
        this.asistenciaHoy = hoy.data
        this.historial = historial.data || []
      } catch (err) {
        console.error('Error:', err)
      } finally {
        this.loading = false
      }
    },
    async marcarEntrada() {
      this.loading = true
      try {
        await authEmpleado.marcarEntrada()
        const notification = useNotification()
        notification.success('¡Entrada registrada correctamente!', 3000)
        await this.cargarDatos()
      } catch (err) {
        const notification = useNotification()
        notification.error(err.response?.data?.message || 'Error al marcar entrada')
      } finally {
        this.loading = false
      }
    },
    async marcarSalida() {
      this.loading = true
      try {
        await authEmpleado.marcarSalida()
        const notification = useNotification()
        notification.success('¡Salida registrada correctamente!', 3000)
        await this.cargarDatos()
      } catch (err) {
        const notification = useNotification()
        notification.error(err.response?.data?.message || 'Error al marcar salida')
      } finally {
        this.loading = false
      }
    },
    formatDate(fecha) {
      return new Date(fecha).toLocaleDateString('es-ES', {
        weekday: 'short',
        day: 'numeric',
        month: 'short'
      })
    },
    calcularHoras(item) {
      if (!item.hora_entrada || !item.hora_salida) return '-'
      const entrada = new Date(`2000-01-01 ${item.hora_entrada}`)
      const salida = new Date(`2000-01-01 ${item.hora_salida}`)
      const diff = Math.floor((salida - entrada) / (1000 * 60))
      const horas = Math.floor(diff / 60)
      const minutos = diff % 60
      return `${horas}h ${minutos}m`
    },
    getEstado(item) {
      if (!item.hora_entrada) return 'Ausente'
      if (item.hora_entrada > '08:15:00') return 'Tardanza'
      if (!item.hora_salida) return 'Incompleta'
      return 'Completo'
    },
    getEstadoClass(item) {
      const estado = this.getEstado(item)
      return {
        'ausente': 'badge-danger',
        'tardanza': 'badge-warning',
        'incompleta': 'badge-info',
        'completo': 'badge-success'
      }[estado] || ''
    }
  }
}
</script>

<style scoped>
.asistencia-container {
  max-width: 900px;
  margin: 0 auto;
}

h1 {
  font-size: 24px;
  font-weight: 700;
  color: #1e293b;
  margin: 0 0 24px;
}

.estado-actual {
  margin-bottom: 28px;
}

.estado-card {
  display: flex;
  align-items: center;
  gap: 20px;
  padding: 28px;
  border-radius: 16px;
}

.estado-card.pending {
  background: linear-gradient(135deg, #f1f5f9 0%, #e2e8f0 100%);
}

.estado-card.in-progress {
  background: linear-gradient(135deg, #dbeafe 0%, #bfdbfe 100%);
}

.estado-card.completed {
  background: linear-gradient(135deg, #dcfce7 0%, #bbf7d0 100%);
}

.estado-icon {
  width: 64px;
  height: 64px;
  border-radius: 16px;
  display: flex;
  align-items: center;
  justify-content: center;
  font-size: 30px;
}

.estado-card.pending .estado-icon {
  background: #e2e8f0;
  color: #64748b;
}

.estado-card.in-progress .estado-icon {
  background: #3b82f6;
  color: white;
}

.estado-card.completed .estado-icon {
  background: #22c55e;
  color: white;
}

.estado-info h3 {
  font-size: 20px;
  font-weight: 600;
  color: #1e293b;
  margin: 0 0 6px;
}

.estado-info p {
  color: #64748b;
  font-size: 15px;
  margin: 0;
}

.botones-marcado {
  display: grid;
  grid-template-columns: 1fr 1fr;
  gap: 16px;
  margin-bottom: 32px;
}

.btn-marcado {
  display: flex;
  align-items: center;
  gap: 16px;
  padding: 24px;
  border: 2px solid #e2e8f0;
  border-radius: 16px;
  background: white;
  cursor: pointer;
  transition: all 0.2s ease;
  position: relative;
  text-align: left;
}

.btn-marcado:disabled {
  opacity: 0.6;
  cursor: not-allowed;
}

.btn-entrada:hover:not(:disabled) {
  border-color: #667eea;
  box-shadow: 0 4px 16px rgba(102, 126, 234, 0.15);
}

.btn-salida:hover:not(:disabled) {
  border-color: #22c55e;
  box-shadow: 0 4px 16px rgba(34, 197, 94, 0.15);
}

.btn-icon {
  width: 56px;
  height: 56px;
  border-radius: 14px;
  display: flex;
  align-items: center;
  justify-content: center;
  font-size: 26px;
}

.btn-entrada .btn-icon {
  background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
  color: white;
}

.btn-salida .btn-icon {
  background: linear-gradient(135deg, #22c55e 0%, #16a34a 100%);
  color: white;
}

.btn-text {
  flex: 1;
}

.btn-title {
  display: block;
  font-size: 18px;
  font-weight: 600;
  color: #1e293b;
}

.btn-desc {
  font-size: 13px;
  color: #64748b;
}

.btn-check {
  width: 28px;
  height: 28px;
  border-radius: 50%;
  display: flex;
  align-items: center;
  justify-content: center;
  font-size: 18px;
  color: #22c55e;
}

.historial-reciente {
  background: white;
  border-radius: 16px;
  padding: 24px;
  border: 1px solid #e2e8f0;
}

.historial-reciente h3 {
  font-size: 16px;
  font-weight: 600;
  color: #1e293b;
  margin: 0 0 20px;
}

.historial-table {
  overflow-x: auto;
}

table {
  width: 100%;
  border-collapse: collapse;
}

th, td {
  padding: 12px 16px;
  text-align: left;
  font-size: 14px;
}

th {
  background: #f8fafc;
  color: #64748b;
  font-weight: 600;
  text-transform: uppercase;
  font-size: 12px;
  letter-spacing: 0.5px;
}

td {
  border-bottom: 1px solid #f1f5f9;
  color: #334155;
}

tr:hover td {
  background: #f8fafc;
}

.estado-badge {
  padding: 4px 10px;
  border-radius: 20px;
  font-size: 12px;
  font-weight: 600;
}

.badge-success {
  background: #dcfce7;
  color: #166534;
}

.badge-warning {
  background: #fef3c7;
  color: #92400e;
}

.badge-danger {
  background: #fee2e2;
  color: #991b1b;
}

.badge-info {
  background: #dbeafe;
  color: #1e40af;
}

@media (max-width: 640px) {
  .botones-marcado {
    grid-template-columns: 1fr;
  }
}
</style>
