// frontend-react/src/views/empleado/MiPerfil.jsx
import { useState, useEffect } from 'react'
import { useNavigate, Link } from 'react-router-dom'
import api from '../../services/api'
import { useToast } from '../../context/ToastContext'

const MiPerfil = () => {
  const navigate = useNavigate()
  const { success, error } = useToast()
  const [empleado, setEmpleado] = useState(null)
  const [sidebarOpen, setSidebarOpen] = useState(false)
  const [editMode, setEditMode] = useState(false)
  const [loading, setLoading] = useState(false)
  const [formData, setFormData] = useState({
    correo: '',
    telefono: ''
  })

  useEffect(() => {
    const token = localStorage.getItem('empleadoToken')
    const emp = localStorage.getItem('empleado')
    if (!token || !emp) { navigate('/login'); return }
    const parsedEmp = JSON.parse(emp)
    setEmpleado(parsedEmp)
    setFormData({
      correo: parsedEmp.correo || '',
      telefono: parsedEmp.telefono || ''
    })
  }, [navigate])

  const logout = () => {
    localStorage.removeItem('empleadoToken')
    localStorage.removeItem('empleado')
    navigate('/login')
  }

  const handleSave = async () => {
    setLoading(true)
    try {
      const response = await api.updatePerfil(formData)
      const updatedEmp = response.data?.data || { ...empleado, ...formData }
      setEmpleado(updatedEmp)
      localStorage.setItem('empleado', JSON.stringify(updatedEmp))
      success(response.data?.message || 'Perfil actualizado correctamente')
      setEditMode(false)
    } catch (err) {
      const errorMsg = err.response?.data?.message || err.message || 'Error al actualizar perfil'
      error(errorMsg)
      console.error('Error updating profile:', err)
    } finally {
      setLoading(false)
    }
  }

  const navItems = [
    { to: '/empleado/dashboard', icon: 'bi-house', label: 'Inicio' },
    { to: '/empleado/asistencia', icon: 'bi-clock', label: 'Asistencia' },
    { to: '/empleado/mis-asistencias', icon: 'bi-calendar-check', label: 'Mis Asistencias' },
    { to: '/empleado/licencias', icon: 'bi-calendar', label: 'Licencias' },
    { to: '/empleado/solicitar-licencia', icon: 'bi-plus-circle', label: 'Solicitar' },
    { to: '/empleado/perfil', icon: 'bi-person', label: 'Mi Perfil', active: true },
  ]

  if (!empleado) return null

  return (
    <div className="flex min-h-screen bg-gray-50">
      <aside className={`fixed inset-y-0 left-0 z-50 w-64 bg-white shadow-lg transform transition-transform duration-300 ${sidebarOpen ? 'translate-x-0' : '-translate-x-full'} md:relative md:translate-x-0`}>
        <div className="p-4 border-b border-gray-100 flex items-center justify-between">
          <div className="flex items-center gap-3">
            <div className="w-10 h-10 rounded-xl flex items-center justify-center text-white bg-gradient-green"><i className="bi bi-person-badge"></i></div>
            <span className="font-semibold text-gray-800">Empleado</span>
          </div>
          <button onClick={() => setSidebarOpen(false)} className="md:hidden text-gray-500">
            <i className="bi bi-x-lg text-xl"></i>
          </button>
        </div>
        <nav className="p-4 space-y-1">
          {navItems.map((item) => (
            <Link key={item.to} to={item.to} onClick={() => setSidebarOpen(false)} className={`flex items-center gap-3 px-4 py-3 rounded-xl transition-all ${item.active ? 'text-white bg-gradient-green' : 'text-gray-600 hover:bg-gray-100'}`}>
              <i className={`bi ${item.icon}`}></i><span>{item.label}</span>
            </Link>
          ))}
        </nav>
        <div className="p-4 border-t border-gray-100">
          <button onClick={logout} className="flex items-center gap-3 px-4 py-3 rounded-xl text-red-600 hover:bg-red-50 w-full"><i className="bi bi-box-arrow-right"></i><span>Cerrar Sesión</span></button>
        </div>
      </aside>

      {sidebarOpen && <div className="fixed inset-0 bg-black/50 z-40 md:hidden" onClick={() => setSidebarOpen(false)}></div>}

      <main className="flex-1 p-4 md:p-8">
        <div className="flex items-center justify-between mb-6 md:mb-8">
          <h1 className="text-2xl md:text-3xl font-bold text-gray-800">Mi Perfil</h1>
          <button onClick={() => setSidebarOpen(true)} className="md:hidden text-gray-600 p-2">
            <i className="bi bi-list text-2xl"></i>
          </button>
        </div>

        <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
          <div className="bg-white rounded-xl p-4 md:p-6 shadow-sm border border-gray-100">
            <div className="flex items-center justify-between mb-6">
              <h2 className="text-lg font-bold text-gray-800">Información Personal</h2>
              {!editMode && (
                <button onClick={() => setEditMode(true)} className="text-green-600 hover:text-green-700 text-sm font-medium">
                  <i className="bi bi-pencil mr-1"></i> Editar
                </button>
              )}
            </div>

            <div className="text-center mb-6">
              <div className="w-24 h-24 mx-auto mb-4 rounded-full flex items-center justify-center text-3xl text-white font-bold bg-gradient-green">
                {empleado.nombre?.[0]}{empleado.apellido?.[0]}
              </div>
              <h3 className="text-xl font-bold text-gray-800">{empleado.nombre} {empleado.apellido}</h3>
              <p className="text-gray-500">{empleado.cargo?.nombre || 'Empleado'}</p>
              <span className="inline-block mt-2 px-3 py-1 bg-green-100 text-green-700 rounded-full text-sm font-medium">{empleado.estado}</span>
            </div>

            <div className="space-y-4">
              <div className="flex items-center gap-4 p-4 bg-gray-50 rounded-xl">
                <div className="w-10 h-10 rounded-lg flex items-center justify-center text-gray-600 bg-gray-200"><i className="bi bi-credit-card"></i></div>
                <div><p className="text-xs text-gray-500">DNI</p><p className="font-semibold text-gray-800">{empleado.dni}</p></div>
              </div>

              <div className="flex items-center gap-4 p-4 bg-gray-50 rounded-xl">
                <div className="w-10 h-10 rounded-lg flex items-center justify-center text-gray-600 bg-gray-200"><i className="bi bi-envelope"></i></div>
                <div className="flex-1">
                  <p className="text-xs text-gray-500">Correo electrónico</p>
                  {editMode ? (
                    <input type="email" value={formData.correo} onChange={(e) => setFormData({...formData, correo: e.target.value})}
                      className="w-full px-2 py-1 rounded border border-gray-300 focus:outline-none focus:ring-2 focus:ring-green-500" placeholder="correo@email.com" />
                  ) : (
                    <p className="font-semibold text-gray-800">{empleado.correo || 'No registrado'}</p>
                  )}
                </div>
              </div>

              <div className="flex items-center gap-4 p-4 bg-gray-50 rounded-xl">
                <div className="w-10 h-10 rounded-lg flex items-center justify-center text-gray-600 bg-gray-200"><i className="bi bi-telephone"></i></div>
                <div className="flex-1">
                  <p className="text-xs text-gray-500">Teléfono</p>
                  {editMode ? (
                    <input type="tel" value={formData.telefono} onChange={(e) => setFormData({...formData, telefono: e.target.value})}
                      className="w-full px-2 py-1 rounded border border-gray-300 focus:outline-none focus:ring-2 focus:ring-green-500" placeholder="951123456" />
                  ) : (
                    <p className="font-semibold text-gray-800">{empleado.telefono || 'No registrado'}</p>
                  )}
                </div>
              </div>
            </div>

            {editMode && (
              <div className="flex gap-3 mt-6">
                <button onClick={() => setEditMode(false)} className="flex-1 py-2 px-4 rounded-lg border border-gray-300 text-gray-600 hover:bg-gray-50">
                  Cancelar
                </button>
                <button onClick={handleSave} disabled={loading} className="flex-1 py-2 px-4 rounded-lg bg-green-600 text-white hover:bg-green-700 disabled:opacity-50">
                  {loading ? 'Guardando...' : 'Guardar cambios'}
                </button>
              </div>
            )}
          </div>

          <div className="space-y-6">
            <div className="bg-white rounded-xl p-4 md:p-6 shadow-sm border border-gray-100">
              <h2 className="text-lg font-bold text-gray-800 mb-4">Información Laboral</h2>
              <div className="space-y-4">
                <div className="flex items-center gap-4 p-4 bg-gray-50 rounded-xl">
                  <div className="w-10 h-10 rounded-lg flex items-center justify-center text-gray-600 bg-gray-200"><i className="bi bi-building"></i></div>
                  <div><p className="text-xs text-gray-500">Departamento</p><p className="font-semibold text-gray-800">{empleado.departamento?.nombre || 'No asignado'}</p></div>
                </div>
                <div className="flex items-center gap-4 p-4 bg-gray-50 rounded-xl">
                  <div className="w-10 h-10 rounded-lg flex items-center justify-center text-gray-600 bg-gray-200"><i className="bi bi-briefcase"></i></div>
                  <div><p className="text-xs text-gray-500">Cargo</p><p className="font-semibold text-gray-800">{empleado.cargo?.nombre || 'Sin cargo'}</p></div>
                </div>
                <div className="flex items-center gap-4 p-4 bg-gray-50 rounded-xl">
                  <div className="w-10 h-10 rounded-lg flex items-center justify-center text-gray-600 bg-gray-200"><i className="bi bi-calendar-plus"></i></div>
                  <div><p className="text-xs text-gray-500">Fecha de Ingreso</p><p className="font-semibold text-gray-800">{empleado.fecha_ingreso || 'No registrada'}</p></div>
                </div>
              </div>
            </div>

            <div className="bg-white rounded-xl p-4 md:p-6 shadow-sm border border-gray-100">
              <h2 className="text-lg font-bold text-gray-800 mb-4">Vacaciones</h2>
              <div className="space-y-4">
                <div className="flex items-center justify-between p-4 bg-gray-50 rounded-xl">
                  <div className="flex items-center gap-3">
                    <div className="w-10 h-10 rounded-lg flex items-center justify-center text-green-600 bg-green-100"><i className="bi bi-calendar-check"></i></div>
                    <div><p className="text-sm text-gray-500">Días disponibles</p><p className="font-bold text-green-600 text-lg">{empleado.dias_vacaciones - (empleado.dias_vacaciones_usados || 0)}</p></div>
                  </div>
                </div>
                <div className="flex items-center justify-between p-4 bg-gray-50 rounded-xl">
                  <div className="flex items-center gap-3">
                    <div className="w-10 h-10 rounded-lg flex items-center justify-center text-yellow-600 bg-yellow-100"><i className="bi bi-calendar-minus"></i></div>
                    <div><p className="text-sm text-gray-500">Días usados</p><p className="font-bold text-yellow-600 text-lg">{empleado.dias_vacaciones_usados || 0}</p></div>
                  </div>
                </div>
                <div className="flex items-center justify-between p-4 bg-gray-50 rounded-xl">
                  <div className="flex items-center gap-3">
                    <div className="w-10 h-10 rounded-lg flex items-center justify-center text-blue-600 bg-blue-100"><i className="bi bi-calendar3"></i></div>
                    <div><p className="text-sm text-gray-500">Total días anuales</p><p className="font-bold text-blue-600 text-lg">{empleado.dias_vacaciones || 0}</p></div>
                  </div>
                </div>
              </div>
            </div>

            <button onClick={logout} className="w-full py-3 rounded-xl text-red-600 font-semibold hover:bg-red-50 flex items-center justify-center gap-2 bg-white shadow-sm border border-gray-100">
              <i className="bi bi-box-arrow-right"></i> Cerrar Sesión
            </button>
          </div>
        </div>
      </main>
    </div>
  )
}

export default MiPerfil

// frontend/src/views/empleado/MiPerfil.vue
<template>
  <EmpleadoLayout>
    <div class="mi-perfil-container">
      <h1>Mi Perfil</h1>

      <div class="perfil-grid">
        <div class="perfil-card info-card">
          <div class="perfil-header">
            <div class="avatar">
              {{ getInitials }}
            </div>
            <div class="perfil-nombre">
              <h2>{{ empleado?.nombre }} {{ empleado?.apellido }}</h2>
              <span>{{ empleado?.cargo?.nombre || 'Empleado' }}</span>
            </div>
          </div>

          <div class="info-section">
            <h3>Datos Personales</h3>
            <div class="info-grid">
              <div class="info-item">
                <span class="label">DNI</span>
                <span class="value">{{ empleado?.dni }}</span>
              </div>
              <div class="info-item">
                <span class="label">Correo</span>
                <span class="value">{{ empleado?.correo || '-' }}</span>
              </div>
              <div class="info-item">
                <span class="label">Teléfono</span>
                <span class="value">{{ empleado?.telefono || '-' }}</span>
              </div>
              <div class="info-item">
                <span class="label">Estado</span>
                <span class="value estado" :class="empleado?.estado?.toLowerCase()">
                  {{ empleado?.estado || '-' }}
                </span>
              </div>
            </div>
          </div>

          <div class="info-section">
            <h3>Datos Laborales</h3>
            <div class="info-grid">
              <div class="info-item">
                <span class="label">Departamento</span>
                <span class="value">{{ empleado?.departamento?.nombre || '-' }}</span>
              </div>
              <div class="info-item">
                <span class="label">Cargo</span>
                <span class="value">{{ empleado?.cargo?.nombre || '-' }}</span>
              </div>
              <div class="info-item">
                <span class="label">Fecha de Ingreso</span>
                <span class="value">{{ formatDate(empleado?.fecha_ingreso) }}</span>
              </div>
              <div class="info-item">
                <span class="label">Vacaciones</span>
                <span class="value">{{ empleado?.dias_vacaciones_usados || 0 }} / 15 días</span>
              </div>
            </div>
          </div>
        </div>

        <div class="perfil-card actions-card">
          <div class="action-section">
            <h3>Editar Información</h3>
            <form @submit.prevent="guardarPerfil" class="edit-form">
              <div class="form-group">
                <label>Correo Electrónico</label>
                <input v-model="form.correo" type="email" class="form-input" />
              </div>
              <div class="form-group">
                <label>Teléfono</label>
                <input v-model="form.telefono" type="tel" class="form-input" />
              </div>
              <button type="submit" class="btn-save" :disabled="loading">
                <span v-if="loading">Guardando...</span>
                <span v-else><i class="bi bi-check-lg"></i> Guardar Cambios</span>
              </button>
            </form>
          </div>

          <div class="action-section">
            <h3>Cambiar Contraseña</h3>
            <form @submit.prevent="cambiarPassword" class="password-form">
              <div class="form-group">
                <label>Contraseña Actual</label>
                <div class="password-input">
                  <input
                    v-model="passwordForm.actual"
                    :type="showPassword.actual ? 'text' : 'password'"
                    class="form-input"
                  />
                  <button type="button" @click="showPassword.actual = !showPassword.actual">
                    <i :class="showPassword.actual ? 'bi bi-eye-slash' : 'bi bi-eye'"></i>
                  </button>
                </div>
              </div>
              <div class="form-group">
                <label>Nueva Contraseña</label>
                <div class="password-input">
                  <input
                    v-model="passwordForm.nueva"
                    :type="showPassword.nueva ? 'text' : 'password'"
                    class="form-input"
                  />
                  <button type="button" @click="showPassword.nueva = !showPassword.nueva">
                    <i :class="showPassword.nueva ? 'bi bi-eye-slash' : 'bi bi-eye'"></i>
                  </button>
                </div>
              </div>
              <div class="form-group">
                <label>Confirmar Contraseña</label>
                <div class="password-input">
                  <input
                    v-model="passwordForm.confirmar"
                    :type="showPassword.confirmar ? 'text' : 'password'"
                    class="form-input"
                  />
                  <button type="button" @click="showPassword.confirmar = !showPassword.confirmar">
                    <i :class="showPassword.confirmar ? 'bi bi-eye-slash' : 'bi bi-eye'"></i>
                  </button>
                </div>
              </div>
              <button type="submit" class="btn-password" :disabled="!puedeCambiarPassword || loading">
                <i class="bi bi-key"></i> Cambiar Contraseña
              </button>
            </form>
          </div>
        </div>
      </div>
    </div>
  </EmpleadoLayout>
</template>

<script>
import EmpleadoLayout from '../../components/empleado/EmpleadoLayout.vue'
import authEmpleado from '../../services/authEmpleado'
import { useNotification } from '../../services/notification.service'

export default {
  name: 'MiPerfil',
  components: {
    EmpleadoLayout
  },
  data() {
    return {
      loading: false,
      form: {
        correo: '',
        telefono: ''
      },
      passwordForm: {
        actual: '',
        nueva: '',
        confirmar: ''
      },
      showPassword: {
        actual: false,
        nueva: false,
        confirmar: false
      }
    }
  },
  computed: {
    empleado() {
      return authEmpleado.getEmpleado()
    },
    getInitials() {
      if (!this.empleado) return '?'
      return `${(this.empleado.nombre || '').charAt(0)}${(this.empleado.apellido || '').charAt(0)}`.toUpperCase()
    },
    puedeCambiarPassword() {
      return (
        this.passwordForm.actual.length > 0 &&
        this.passwordForm.nueva.length >= 6 &&
        this.passwordForm.nueva === this.passwordForm.confirmar
      )
    }
  },
  mounted() {
    this.cargarDatos()
  },
  methods: {
    cargarDatos() {
      if (this.empleado) {
        this.form.correo = this.empleado.correo || ''
        this.form.telefono = this.empleado.telefono || ''
      }
    },
    formatDate(fecha) {
      if (!fecha) return '-'
      return new Date(fecha).toLocaleDateString('es-ES', {
        day: '2-digit',
        month: 'long',
        year: 'numeric'
      })
    },
    async guardarPerfil() {
      this.loading = true
      try {
        await authEmpleado.updatePerfil(this.form)
        
        const user = authEmpleado.getEmpleado()
        user.correo = this.form.correo
        user.telefono = this.form.telefono
        localStorage.setItem('empleadoUser', JSON.stringify(user))
        
        const notification = useNotification()
        notification.success('Información actualizada correctamente')
      } catch (err) {
        const notification = useNotification()
        notification.error(err.response?.data?.message || 'Error al guardar')
      } finally {
        this.loading = false
      }
    },
    async cambiarPassword() {
      if (!this.puedeCambiarPassword) return
      
      this.loading = true
      try {
        await authEmpleado.cambiarPassword({
          password_actual: this.passwordForm.actual,
          password_nueva: this.passwordForm.nueva
        })
        
        this.passwordForm = { actual: '', nueva: '', confirmar: '' }
        
        const notification = useNotification()
        notification.success('Contraseña cambiada correctamente')
      } catch (err) {
        const notification = useNotification()
        notification.error(err.response?.data?.message || 'Error al cambiar contraseña')
      } finally {
        this.loading = false
      }
    }
  }
}
</script>

<style scoped>
.mi-perfil-container {
  max-width: 1000px;
  margin: 0 auto;
}

h1 {
  font-size: 24px;
  font-weight: 700;
  color: #1e293b;
  margin: 0 0 24px;
}

.perfil-grid {
  display: grid;
  grid-template-columns: 1fr 1fr;
  gap: 24px;
}

.perfil-card {
  background: white;
  border-radius: 16px;
  padding: 28px;
  border: 1px solid #e2e8f0;
}

.perfil-header {
  display: flex;
  align-items: center;
  gap: 16px;
  margin-bottom: 28px;
  padding-bottom: 20px;
  border-bottom: 1px solid #f1f5f9;
}

.avatar {
  width: 72px;
  height: 72px;
  background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
  border-radius: 20px;
  display: flex;
  align-items: center;
  justify-content: center;
  color: white;
  font-size: 26px;
  font-weight: 700;
}

.perfil-nombre h2 {
  font-size: 22px;
  font-weight: 700;
  color: #1e293b;
  margin: 0 0 4px;
}

.perfil-nombre span {
  font-size: 14px;
  color: #64748b;
}

.info-section {
  margin-bottom: 24px;
}

.info-section:last-child {
  margin-bottom: 0;
}

.info-section h3 {
  font-size: 14px;
  font-weight: 600;
  color: #64748b;
  text-transform: uppercase;
  letter-spacing: 0.5px;
  margin: 0 0 16px;
}

.info-grid {
  display: grid;
  grid-template-columns: 1fr 1fr;
  gap: 16px;
}

.info-item {
  display: flex;
  flex-direction: column;
  gap: 4px;
}

.info-item .label {
  font-size: 12px;
  color: #94a3b8;
}

.info-item .value {
  font-size: 14px;
  font-weight: 500;
  color: #1e293b;
}

.info-item .value.activo {
  color: #22c55e;
}

.info-item .value.inactivo {
  color: #ef4444;
}

.action-section {
  margin-bottom: 32px;
}

.action-section:last-child {
  margin-bottom: 0;
  padding-top: 24px;
  border-top: 1px solid #f1f5f9;
}

.action-section h3 {
  font-size: 16px;
  font-weight: 600;
  color: #1e293b;
  margin: 0 0 20px;
}

.form-group {
  margin-bottom: 16px;
}

.form-group label {
  display: block;
  font-size: 13px;
  font-weight: 500;
  color: #475569;
  margin-bottom: 6px;
}

.form-input {
  width: 100%;
  padding: 12px 14px;
  border: 2px solid #e2e8f0;
  border-radius: 10px;
  font-size: 14px;
  font-family: inherit;
  transition: all 0.2s ease;
}

.form-input:focus {
  outline: none;
  border-color: #667eea;
  box-shadow: 0 0 0 4px rgba(102, 126, 234, 0.1);
}

.password-input {
  position: relative;
}

.password-input input {
  padding-right: 44px;
}

.password-input button {
  position: absolute;
  right: 12px;
  top: 50%;
  transform: translateY(-50%);
  background: none;
  border: none;
  color: #94a3b8;
  cursor: pointer;
  padding: 4px;
}

.btn-save,
.btn-password {
  width: 100%;
  padding: 14px 20px;
  border-radius: 10px;
  font-weight: 600;
  cursor: pointer;
  display: flex;
  align-items: center;
  justify-content: center;
  gap: 8px;
  font-size: 15px;
  transition: all 0.2s ease;
}

.btn-save {
  background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
  border: none;
  color: white;
}

.btn-save:hover:not(:disabled) {
  transform: translateY(-2px);
  box-shadow: 0 4px 15px rgba(102, 126, 234, 0.3);
}

.btn-password {
  background: #f1f5f9;
  border: 2px solid #e2e8f0;
  color: #475569;
}

.btn-password:hover:not(:disabled) {
  background: #e2e8f0;
}

.btn-save:disabled,
.btn-password:disabled {
  opacity: 0.6;
  cursor: not-allowed;
  transform: none;
}

@media (max-width: 768px) {
  .perfil-grid {
    grid-template-columns: 1fr;
  }

  .info-grid {
    grid-template-columns: 1fr;
  }
}
</style>
