// frontend/src/App.vue
<template>
  <div id="app">
    <nav class="navbar navbar-expand-lg navbar-dark bg-primary">
      <div class="container-fluid">
        <router-link to="/" class="navbar-brand">
          <i class="bi bi-people-fill"></i> Sistema de Empleados
        </router-link>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
          <ul class="navbar-nav ms-auto">
            <li class="nav-item" v-if="isLoggedIn">
              <router-link to="/empleados" class="nav-link">
                <i class="bi bi-people"></i> Empleados
              </router-link>
            </li>
            <li class="nav-item" v-if="isLoggedIn">
              <router-link to="/asistencias" class="nav-link">
                <i class="bi bi-clock"></i> Asistencias
              </router-link>
            </li>
            <li class="nav-item" v-if="isLoggedIn">
              <router-link to="/licencias" class="nav-link">
                <i class="bi bi-calendar"></i> Licencias
              </router-link>
            </li>
            <li class="nav-item" v-if="isLoggedIn">
              <router-link to="/auditoria" class="nav-link">
                <i class="bi bi-clock-history"></i> Auditoría
              </router-link>
            </li>
            <li class="nav-item" v-if="isLoggedIn">
              <router-link to="/graficos" class="nav-link">
                <i class="bi bi-graph-up"></i> Gráficos
              </router-link>
            </li>
            <li class="nav-item" v-if="isLoggedIn">
              <ThemeToggle />
            </li>
            <li class="nav-item" v-if="isLoggedIn">
              <button @click="logout" class="btn btn-outline-light btn-sm ms-2">
                <i class="bi bi-box-arrow-right"></i> Salir
              </button>
            </li>
          </ul>
        </div>
      </div>
    </nav>
    <main class="container mt-4">
      <router-view />
    </main>
    <ToastContainer />
  </div>
</template>

<script>
import ToastContainer from './components/ToastContainer.vue'
import ThemeToggle from './components/ThemeToggle.vue'
import { useTheme } from './services/theme.service'

export default {
  name: 'App',
  components: {
    ToastContainer,
    ThemeToggle
  },
  data() {
    return {
      isLoggedIn: false
    }
  },
  mounted() {
    this.isLoggedIn = !!localStorage.getItem('token')
    const theme = useTheme()
    theme.initTheme()
  },
  methods: {
    logout() {
      localStorage.removeItem('token')
      localStorage.removeItem('usuario')
      this.$router.push('/login')
      this.isLoggedIn = false
    }
  },
  watch: {
    $route() {
      this.isLoggedIn = !!localStorage.getItem('token')
    }
  }
}
</script>

<style>
body {
  background-color: #f8f9fa;
}

.navbar {
  box-shadow: 0 2px 4px rgba(0,0,0,0.1);
}

main {
  min-height: calc(100vh - 60px);
}
</style>

// frontend-react/src/App.jsx
import { useState, useEffect } from 'react'
import { Link, useLocation, useNavigate } from 'react-router-dom'
import Router from './router'

function App() {
  const location = useLocation()
  const navigate = useNavigate()
  const [isLoggedIn, setIsLoggedIn] = useState(false)

  useEffect(() => {
    const token = localStorage.getItem('token')
    setIsLoggedIn(!!token)
  }, [location])

  const logout = () => {
    localStorage.removeItem('token')
    localStorage.removeItem('usuario')
    localStorage.removeItem('empleadoToken')
    localStorage.removeItem('empleado')
    setIsLoggedIn(false)
    navigate('/login')
  }

  const showNavbar = isLoggedIn && !location.pathname.startsWith('/empleado')

  return (
    <div id="app">
      {showNavbar && (
        <nav className="bg-gradient-to-r from-purple-600 to-indigo-600 shadow-lg">
          <div className="container mx-auto px-4">
            <div className="flex justify-between items-center h-16">
              <Link to="/" className="flex items-center gap-2 text-white font-semibold text-lg">
                <i className="bi bi-people-fill text-xl"></i>
                Sistema de Empleados
              </Link>
              <div className="hidden md:flex items-center gap-1">
                <Link to="/empleados" className={`px-4 py-2 rounded-lg text-white hover:bg-white/10 transition-colors ${location.pathname === '/empleados' ? 'bg-white/20' : ''}`}>
                  <i className="bi bi-people mr-2"></i>Empleados
                </Link>
                <Link to="/asistencias" className={`px-4 py-2 rounded-lg text-white hover:bg-white/10 transition-colors ${location.pathname === '/asistencias' ? 'bg-white/20' : ''}`}>
                  <i className="bi bi-clock mr-2"></i>Asistencias
                </Link>
                <Link to="/licencias" className={`px-4 py-2 rounded-lg text-white hover:bg-white/10 transition-colors ${location.pathname === '/licencias' ? 'bg-white/20' : ''}`}>
                  <i className="bi bi-calendar mr-2"></i>Licencias
                </Link>
                <Link to="/auditoria" className={`px-4 py-2 rounded-lg text-white hover:bg-white/10 transition-colors ${location.pathname === '/auditoria' ? 'bg-white/20' : ''}`}>
                  <i className="bi bi-clock-history mr-2"></i>Auditoria
                </Link>
                <Link to="/graficos" className={`px-4 py-2 rounded-lg text-white hover:bg-white/10 transition-colors ${location.pathname === '/graficos' ? 'bg-white/20' : ''}`}>
                  <i className="bi bi-graph-up mr-2"></i>Graficos
                </Link>
                <button onClick={logout} className="ml-4 px-4 py-2 rounded-lg border border-white/30 text-white hover:bg-white/10 transition-colors text-sm">
                  <i className="bi bi-box-arrow-right mr-1"></i>Salir
                </button>
              </div>
            </div>
          </div>
        </nav>
      )}
      
      <Router />
    </div>
  )
}

export default App
