// frontend-react/src/views/Empleados.jsx
import { useState, useEffect } from 'react'
import api from '../services/api'
import { useToast } from '../context/ToastContext'
import { exportEmployeesToPDF } from '../utils/exportPDF'
import { exportEmployeesToExcel } from '../utils/exportExcel'

const Empleados = () => {
  const { success, error } = useToast()
  const [empleados, setEmpleados] = useState([])
  const [loading, setLoading] = useState(true)
  const [searchQuery, setSearchQuery] = useState('')
  const [showModal, setShowModal] = useState(false)
  const [editingEmpleado, setEditingEmpleado] = useState(null)
  const [formData, setFormData] = useState({
    nombre: '',
    apellido: '',
    dni: '',
    correo: '',
    telefono: '',
    departamentoId: '',
    cargoId: '',
    estado: 'Activo'
  })
  const [departamentos, setDepartamentos] = useState([])
  const [cargos, setCargos] = useState([])

  useEffect(() => {
    loadEmpleados()
    loadDepartamentos()
    loadCargos()
  }, [])

  const loadEmpleados = async () => {
    try {
      setLoading(true)
      const response = await api.getEmpleados()
      setEmpleados(response.data)
    } catch (err) {
      console.error('Error:', err)
    } finally {
      setLoading(false)
    }
  }

  const loadDepartamentos = async () => {
    try {
      const response = await api.getDepartamentos()
      setDepartamentos(response.data)
    } catch (err) {
      console.error('Error:', err)
    }
  }

  const loadCargos = async () => {
    try {
      const response = await api.getCargos()
      setCargos(response.data)
    } catch (err) {
      console.error('Error:', err)
    }
  }

  const filteredEmpleados = empleados.filter(emp => {
    const query = searchQuery.toLowerCase()
    return (
      emp.nombre?.toLowerCase().includes(query) ||
      emp.apellido?.toLowerCase().includes(query) ||
      emp.dni?.includes(query) ||
      emp.correo?.toLowerCase().includes(query)
    )
  })

  const handleSubmit = async (e) => {
    e.preventDefault()
    try {
      if (editingEmpleado) {
        await api.updateEmpleado(editingEmpleado.id, formData)
        success('Empleado actualizado correctamente')
      } else {
        await api.createEmpleado(formData)
        success('Empleado creado correctamente')
      }
      loadEmpleados()
      setShowModal(false)
      resetForm()
    } catch (err) {
      error('Error al guardar empleado')
      console.error('Error:', err)
    }
  }

  const handleEdit = (empleado) => {
    setEditingEmpleado(empleado)
    setFormData({
      nombre: empleado.nombre,
      apellido: empleado.apellido,
      dni: empleado.dni,
      correo: empleado.correo || '',
      telefono: empleado.telefono || '',
      departamentoId: empleado.departamentoId,
      cargoId: empleado.cargoId,
      estado: empleado.estado
    })
    setShowModal(true)
  }

  const handleDelete = async (id) => {
    if (window.confirm('¿Estás seguro de eliminar este empleado?')) {
      try {
        await api.deleteEmpleado(id)
        loadEmpleados()
        success('Empleado eliminado correctamente')
      } catch (err) {
        error('Error al eliminar empleado')
        console.error('Error:', err)
      }
    }
  }

  const handleExportPDF = () => {
    exportEmployeesToPDF(empleados)
    success('PDF exportado correctamente')
  }

  const handleExportExcel = () => {
    exportEmployeesToExcel(empleados)
    success('Excel exportado correctamente')
  }

  const resetForm = () => {
    setEditingEmpleado(null)
    setFormData({
      nombre: '',
      apellido: '',
      dni: '',
      correo: '',
      telefono: '',
      departamentoId: '',
      cargoId: '',
      estado: 'Activo'
    })
  }

  const getInitials = (nombre, apellido) => {
    return `${nombre?.[0] || ''}${apellido?.[0] || ''}`.toUpperCase()
  }

  return (
    <div className="p-8">
      <div className="flex justify-between items-center mb-6 flex-wrap gap-4">
        <div className="flex items-center gap-4">
          <div className="w-12 h-12 rounded-xl flex items-center justify-center text-white text-xl bg-gradient-purple shadow-gradient-purple">
            <i className="bi bi-people-fill"></i>
          </div>
          <div>
            <h1 className="text-2xl font-bold text-gray-800">Gestión de Empleados</h1>
            <p className="text-gray-500 text-sm">Administra la información de todos los empleados</p>
          </div>
        </div>
        <button onClick={() => { resetForm(); setShowModal(true); }} 
                className="px-4 py-2 rounded-lg text-white font-medium flex items-center gap-2 transition-all hover:shadow-lg bg-gradient-purple shadow-gradient-purple">
          <i className="bi bi-plus-lg"></i>
          Nuevo Empleado
        </button>
      </div>

      <div className="flex gap-4 mb-6 items-center flex-wrap">
        <div className="relative flex-1 max-w-md">
          <input 
            type="text" 
            placeholder="Buscar por nombre, DNI o correo..."
            value={searchQuery}
            onChange={(e) => setSearchQuery(e.target.value)}
            className="w-full px-4 py-2 pl-10 rounded-lg border border-gray-200 focus:outline-none focus:ring-2 focus:ring-purple-500"
          />
          <i className="bi bi-search absolute left-3 top-1/2 -translate-y-1/2 text-gray-400"></i>
          {searchQuery && (
            <button onClick={() => setSearchQuery('')} className="absolute right-3 top-1/2 -translate-y-1/2 text-gray-400 hover:text-gray-600">
              <i className="bi bi-x"></i>
            </button>
          )}
        </div>
        <div className="bg-white px-3 py-1 rounded-lg border border-gray-200">
          <span className="text-purple-600 font-semibold">{filteredEmpleados.length}</span>
          <span className="text-gray-500 text-sm ml-1">empleados</span>
        </div>
        <div className="flex gap-2">
          <button onClick={handleExportPDF} className="px-3 py-2 rounded-lg border border-gray-200 text-gray-600 hover:bg-gray-50 flex items-center gap-2">
            <i className="bi bi-file-earmark-pdf text-red-500"></i> PDF
          </button>
          <button onClick={handleExportExcel} className="px-3 py-2 rounded-lg border border-gray-200 text-gray-600 hover:bg-gray-50 flex items-center gap-2">
            <i className="bi bi-file-earmark-excel text-green-500"></i> Excel
          </button>
        </div>
      </div>

      {loading ? (
        <div className="flex justify-center items-center py-12">
          <div className="w-10 h-10 border-4 border-purple-500 border-t-transparent rounded-full animate-spin"></div>
        </div>
      ) : filteredEmpleados.length === 0 ? (
        <div className="text-center py-12 bg-white rounded-xl shadow-sm">
          <div className="w-20 h-20 mx-auto mb-4 rounded-full flex items-center justify-center text-4xl text-gray-300 bg-gray-100">
            <i className="bi bi-people"></i>
          </div>
          <h3 className="text-xl font-semibold text-gray-700 mb-2">No hay empleados registrados</h3>
          <p className="text-gray-500 mb-4">Comienza agregando tu primer empleado al sistema</p>
          <button onClick={() => setShowModal(true)} 
                  className="px-4 py-2 rounded-lg text-white inline-flex items-center gap-2 bg-gradient-purple">
            <i className="bi bi-plus-lg"></i> Crear Empleado
          </button>
        </div>
      ) : (
        <div className="bg-white rounded-xl shadow-sm border border-gray-100 overflow-hidden">
          <table className="w-full">
            <thead>
              <tr className="bg-gray-50">
                <th className="px-4 py-3 text-left text-sm font-semibold text-gray-600">#</th>
                <th className="px-4 py-3 text-left text-sm font-semibold text-gray-600">Nombre Completo</th>
                <th className="px-4 py-3 text-left text-sm font-semibold text-gray-600">DNI</th>
                <th className="px-4 py-3 text-left text-sm font-semibold text-gray-600">Correo</th>
                <th className="px-4 py-3 text-left text-sm font-semibold text-gray-600">Departamento</th>
                <th className="px-4 py-3 text-left text-sm font-semibold text-gray-600">Estado</th>
                <th className="px-4 py-3 text-left text-sm font-semibold text-gray-600">Acciones</th>
              </tr>
            </thead>
            <tbody>
              {filteredEmpleados.map((empleado, index) => (
                <tr key={empleado.id} className={`border-t border-gray-100 hover ${empleado.estado === 'In:bg-gray-50activo' ? 'opacity-60' : ''}`}>
                  <td className="px-4 py-3 text-sm text-gray-700">{index + 1}</td>
                  <td className="px-4 py-3">
                    <div className="flex items-center gap-3">
<div className="w-8 h-8 rounded-full flex items-center justify-center text-white text-xs font-bold bg-gradient-purple">
                        {getInitials(empleado.nombre, empleado.apellido)}
                      </div>
                      <div>
                        <div className="font-medium text-gray-800">{empleado.nombre} {empleado.apellido}</div>
                        <div className="text-xs text-gray-500">{empleado.cargo?.nombre || 'Sin cargo'}</div>
                      </div>
                    </div>
                  </td>
                  <td className="px-4 py-3">
                    <span className="px-2 py-1 rounded-lg text-xs font-medium bg-gray-100 text-gray-700">{empleado.dni}</span>
                  </td>
                  <td className="px-4 py-3 text-sm text-gray-700">{empleado.correo || '-'}</td>
                  <td className="px-4 py-3">
                    <span className="px-2 py-1 rounded-lg text-xs font-medium bg-purple-100 text-purple-700">
                      {empleado.departamento?.nombre || '-'}
                    </span>
                  </td>
                  <td className="px-4 py-3">
                    <span className={`px-2 py-1 rounded-full text-xs font-medium ${empleado.estado === 'Activo' ? 'bg-green-100 text-green-700' : 'bg-gray-100 text-gray-700'}`}>
                      {empleado.estado}
                    </span>
                  </td>
                  <td className="px-4 py-3">
                    <div className="flex gap-2">
                      <button onClick={() => handleEdit(empleado)} 
                              className="w-8 h-8 rounded-lg flex items-center justify-center text-sm hover:bg-gray-100" 
                              title="Editar">
                        <i className="bi bi-pencil text-gray-600"></i>
                      </button>
                      <button onClick={() => handleDelete(empleado.id)} 
                              className="w-8 h-8 rounded-lg flex items-center justify-center text-sm hover:bg-red-50" 
                              title="Eliminar">
                        <i className="bi bi-trash text-red-500"></i>
                      </button>
                    </div>
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      )}

      {showModal && (
        <div className="fixed inset-0 bg-black bg-opacity-50 flex items-center justify-center z-50 p-4" onClick={() => setShowModal(false)}>
          <div className="bg-white rounded-xl shadow-xl w-full max-w-lg" onClick={e => e.stopPropagation()}>
            <div className="flex justify-between items-center p-4 border-b">
              <h3 className="text-lg font-semibold">{editingEmpleado ? 'Editar Empleado' : 'Nuevo Empleado'}</h3>
              <button onClick={() => setShowModal(false)} className="bg-transparent border-none text-2xl text-gray-500 cursor-pointer">
                <i className="bi bi-x-lg"></i>
              </button>
            </div>
            <form onSubmit={handleSubmit} className="p-4">
              <div className="grid grid-cols-2 gap-4">
                <div>
                  <label className="block text-sm font-medium text-gray-700 mb-1">Nombre</label>
                  <input 
                    type="text" 
                    value={formData.nombre}
                    onChange={e => setFormData({...formData, nombre: e.target.value})}
                    className="w-full px-3 py-2 rounded-lg border border-gray-200 focus:outline-none focus:ring-2 focus:ring-purple-500"
                    required 
                  />
                </div>
                <div>
                  <label className="block text-sm font-medium text-gray-700 mb-1">Apellido</label>
                  <input 
                    type="text" 
                    value={formData.apellido}
                    onChange={e => setFormData({...formData, apellido: e.target.value})}
                    className="w-full px-3 py-2 rounded-lg border border-gray-200 focus:outline-none focus:ring-2 focus:ring-purple-500"
                    required 
                  />
                </div>
              </div>
              <div className="grid grid-cols-2 gap-4 mt-4">
                <div>
                  <label className="block text-sm font-medium text-gray-700 mb-1">DNI</label>
                  <input 
                    type="text" 
                    value={formData.dni}
                    onChange={e => setFormData({...formData, dni: e.target.value})}
                    className="w-full px-3 py-2 rounded-lg border border-gray-200 focus:outline-none focus:ring-2 focus:ring-purple-500"
                    required 
                  />
                </div>
                <div>
                  <label className="block text-sm font-medium text-gray-700 mb-1">Correo</label>
                  <input 
                    type="email" 
                    value={formData.correo}
                    onChange={e => setFormData({...formData, correo: e.target.value})}
                    className="w-full px-3 py-2 rounded-lg border border-gray-200 focus:outline-none focus:ring-2 focus:ring-purple-500"
                  />
                </div>
              </div>
              <div className="grid grid-cols-2 gap-4 mt-4">
                <div>
                  <label className="block text-sm font-medium text-gray-700 mb-1">Teléfono</label>
                  <input 
                    type="text" 
                    value={formData.telefono}
                    onChange={e => setFormData({...formData, telefono: e.target.value})}
                    className="w-full px-3 py-2 rounded-lg border border-gray-200 focus:outline-none focus:ring-2 focus:ring-purple-500"
                  />
                </div>
                <div>
                  <label className="block text-sm font-medium text-gray-700 mb-1">Departamento</label>
                  <select 
                    value={formData.departamentoId}
                    onChange={e => setFormData({...formData, departamentoId: e.target.value})}
                    className="w-full px-3 py-2 rounded-lg border border-gray-200 focus:outline-none focus:ring-2 focus:ring-purple-500"
                  >
                    <option value="">Seleccionar</option>
                    {departamentos.map(dept => (
                      <option key={dept.id} value={dept.id}>{dept.nombre}</option>
                    ))}
                  </select>
                </div>
              </div>
              <div className="grid grid-cols-2 gap-4 mt-4">
                <div>
                  <label className="block text-sm font-medium text-gray-700 mb-1">Cargo</label>
                  <select 
                    value={formData.cargoId}
                    onChange={e => setFormData({...formData, cargoId: e.target.value})}
                    className="w-full px-3 py-2 rounded-lg border border-gray-200 focus:outline-none focus:ring-2 focus:ring-purple-500"
                  >
                    <option value="">Seleccionar</option>
                    {cargos.map(cargo => (
                      <option key={cargo.id} value={cargo.id}>{cargo.nombre}</option>
                    ))}
                  </select>
                </div>
                <div>
                  <label className="block text-sm font-medium text-gray-700 mb-1">Estado</label>
                  <select 
                    value={formData.estado}
                    onChange={e => setFormData({...formData, estado: e.target.value})}
                    className="w-full px-3 py-2 rounded-lg border border-gray-200 focus:outline-none focus:ring-2 focus:ring-purple-500"
                  >
                    <option value="Activo">Activo</option>
                    <option value="Inactivo">Inactivo</option>
                  </select>
                </div>
              </div>
              <div className="flex justify-end gap-3 mt-6">
                <button type="button" onClick={() => setShowModal(false)} className="px-4 py-2 rounded-lg border border-gray-200 text-gray-600 hover:bg-gray-50">
                  Cancelar
                </button>
                <button type="submit" className="px-4 py-2 rounded-lg text-white bg-gradient-purple">
                  {editingEmpleado ? 'Actualizar' : 'Crear'}
                </button>
              </div>
            </form>
          </div>
        </div>
      )}
    </div>
  )
}

export default Empleados

// frontend/src/views/Empleados.vue
<template>
  <div class="empleados-container">
    <!-- Header -->
    <div class="empleados-header">
      <div class="header-left">
        <h1 class="page-title">
          <i class="bi bi-people-fill"></i> Gestión de Empleados
        </h1>
        <p class="page-subtitle">Administra la información de todos los empleados</p>
      </div>
      <button @click="showModal = true" class="btn-new">
        <i class="bi bi-plus-lg"></i> Nuevo Empleado
      </button>
    </div>

    <!-- Search & Filter Bar -->
    <div class="search-bar">
      <div class="search-input-wrapper">
        <i class="bi bi-search"></i>
        <input 
          type="text" 
          placeholder="Buscar por nombre, DNI o correo..."
          v-model="searchQuery"
          class="search-input"
        />
      </div>
      <div class="result-count">
        {{ filteredEmpleados.length }} registros
      </div>
    </div>

    <!-- Empty State -->
    <div v-if="empleados.length === 0" class="empty-state">
      <div class="empty-icon">
        <i class="bi bi-inbox"></i>
      </div>
      <h3>No hay empleados registrados</h3>
      <p>Comienza agregando tu primer empleado al sistema</p>
      <button @click="showModal = true" class="btn-empty">
        <i class="bi bi-plus-lg"></i> Crear Empleado
      </button>
    </div>

    <!-- Table Card -->
    <div v-else class="table-card">
      <div class="table-wrapper">
        <table class="empleados-table">
          <thead>
            <tr>
              <th class="col-name">
                <i class="bi bi-person"></i> Nombre
              </th>
              <th class="col-dni">
                <i class="bi bi-id-card"></i> DNI
              </th>
              <th class="col-email">
                <i class="bi bi-envelope"></i> Correo
              </th>
              <th class="col-dept">
                <i class="bi bi-building"></i> Departamento
              </th>
              <th class="col-actions">Acciones</th>
            </tr>
          </thead>
          <tbody>
            <tr v-for="empleado in paginatedEmpleados" :key="empleado.id" class="table-row">
              <td class="col-name">
                <div class="employee-cell">
                  <div class="employee-avatar">
                    {{ getInitials(empleado.nombre, empleado.apellido) }}
                  </div>
                  <div class="employee-info">
                    <span class="employee-name">{{ empleado.nombre }} {{ empleado.apellido }}</span>
                  </div>
                </div>
              </td>
              <td class="col-dni">
                <span class="badge-dni">{{ empleado.dni }}</span>
              </td>
              <td class="col-email">
                <span class="email-text">{{ empleado.correo }}</span>
              </td>
              <td class="col-dept">
                <span class="dept-badge">{{ empleado.departamento?.nombre || '-' }}</span>
              </td>
              <td class="col-actions">
                <button 
                  @click="editEmpleado(empleado)" 
                  class="btn-action btn-edit"
                  title="Editar"
                >
                  <i class="bi bi-pencil-fill"></i>
                </button>
                <button 
                  @click="deleteEmpleado(empleado.id)" 
                  class="btn-action btn-delete"
                  title="Eliminar"
                >
                  <i class="bi bi-trash-fill"></i>
                </button>
              </td>
            </tr>
          </tbody>
        </table>
      </div>

      <!-- Pagination Component -->
      <Pagination
        v-model="currentPage"
        :total="filteredEmpleados.length"
        :items-per-page="itemsPerPage"
        @update:items-per-page="itemsPerPage = $event"
      />
    </div>

    <!-- Modal -->
    <transition name="modal">
      <div v-if="showModal" class="modal-overlay">
        <div class="modal-content">
          <div class="modal-header">
            <h2>{{ editingId ? 'Editar Empleado' : 'Nuevo Empleado' }}</h2>
            <button type="button" class="btn-close" @click="closeModal">
              <i class="bi bi-x-lg"></i>
            </button>
          </div>

          <form @submit.prevent="saveEmpleado" class="modal-form">
            <div class="form-group">
              <label>Nombre</label>
              <input 
                v-model="formData.nombre" 
                type="text" 
                placeholder="Ingrese nombre"
                required 
              />
            </div>

            <div class="form-group">
              <label>Apellido</label>
              <input 
                v-model="formData.apellido" 
                type="text" 
                placeholder="Ingrese apellido"
                required 
              />
            </div>

            <div class="form-group">
              <label>DNI</label>
              <input 
                v-model="formData.dni" 
                type="text" 
                placeholder="Ingrese DNI"
                required 
              />
            </div>

            <div class="form-group">
              <label>Correo Electrónico</label>
              <input 
                v-model="formData.correo" 
                type="email" 
                placeholder="correo@ejemplo.com"
              />
            </div>

            <div class="modal-actions">
              <button type="button" @click="closeModal" class="btn-cancel">
                Cancelar
              </button>
              <button type="submit" class="btn-submit">
                <i class="bi bi-check-lg"></i> {{ editingId ? 'Actualizar' : 'Guardar' }}
              </button>
            </div>
          </form>
        </div>
      </div>
    </transition>

    <!-- Delete Confirmation Modal -->
    <transition name="modal">
      <div v-if="showDeleteConfirm" class="modal-overlay">
        <div class="modal-confirm">
          <div class="confirm-icon">
            <i class="bi bi-exclamation-circle"></i>
          </div>
          <h3>Confirmar eliminación</h3>
          <p>¿Está seguro de que desea eliminar este empleado? Esta acción no se puede deshacer.</p>
          <div class="confirm-actions">
            <button @click="showDeleteConfirm = false" class="btn-cancel">
              Cancelar
            </button>
            <button @click="confirmDelete" class="btn-delete-confirm">
              <i class="bi bi-trash-fill"></i> Eliminar
            </button>
          </div>
        </div>
      </div>
    </transition>
  </div>
</template>

<script>
import api from '../services/api'
import { useNotification } from '../services/notification.service'
import Pagination from '../components/Pagination.vue'

export default {
  name: 'Empleados',
  components: {
    Pagination
  },
  data() {
    return {
      empleados: [],
      showModal: false,
      showDeleteConfirm: false,
      deleteId: null,
      editingId: null,
      searchQuery: '',
      currentPage: 1,
      itemsPerPage: 10,
      notification: useNotification(),
      formData: {
        nombre: '',
        apellido: '',
        dni: '',
        correo: ''
      }
    }
  },
  computed: {
    filteredEmpleados() {
      if (!this.searchQuery) return this.empleados
      
      const query = this.searchQuery.toLowerCase()
      return this.empleados.filter(emp => 
        `${emp.nombre} ${emp.apellido}`.toLowerCase().includes(query) ||
        emp.dni.toLowerCase().includes(query) ||
        emp.correo.toLowerCase().includes(query)
      )
    },
    paginatedEmpleados() {
      const start = (this.currentPage - 1) * this.itemsPerPage
      const end = start + this.itemsPerPage
      return this.filteredEmpleados.slice(start, end)
    }
  },
  mounted() {
    this.loadEmpleados()
  },
  methods: {
    async loadEmpleados() {
      try {
        const response = await api.getEmpleados()
        this.empleados = response.data || []
        this.notification.info('Empleados cargados', 2000)
      } catch (err) {
        console.error('Error cargando empleados:', err)
        this.notification.error('Error al cargar empleados')
      }
    },
    editEmpleado(empleado) {
      this.editingId = empleado.id
      this.formData = { ...empleado }
      this.showModal = true
    },
    async saveEmpleado() {
      try {
        const isCreating = !this.editingId
        if (this.editingId) {
          await api.updateEmpleado(this.editingId, this.formData)
          this.notification.success('Empleado actualizado correctamente')
        } else {
          await api.createEmpleado(this.formData)
          this.notification.success('Empleado creado correctamente')
        }
        this.closeModal()
        this.loadEmpleados()
      } catch (err) {
        this.notification.error('Error guardando empleado')
        console.error(err)
      }
    },
    deleteEmpleado(id) {
      this.deleteId = id
      this.showDeleteConfirm = true
    },
    async confirmDelete() {
      try {
        await api.deleteEmpleado(this.deleteId)
        this.notification.success('Empleado eliminado correctamente')
        this.showDeleteConfirm = false
        this.deleteId = null
        this.loadEmpleados()
      } catch (err) {
        this.notification.error('Error al eliminar empleado')
        console.error(err)
      }
    },
    closeModal() {
      this.showModal = false
      this.resetForm()
    },
    resetForm() {
      this.formData = { nombre: '', apellido: '', dni: '', correo: '' }
      this.editingId = null
    },
    getInitials(nombre, apellido) {
      return `${(nombre || '').charAt(0)}${(apellido || '').charAt(0)}`.toUpperCase()
    }
  }
}
</script>

<style scoped>
* {
  margin: 0;
  padding: 0;
  box-sizing: border-box;
}

.empleados-container {
  background: linear-gradient(135deg, #f5f7fa 0%, #f0f4f8 100%);
  min-height: 100vh;
  padding: 32px 20px;
  font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
}

/* Header */
.empleados-header {
  display: flex;
  justify-content: space-between;
  align-items: flex-start;
  gap: 20px;
  margin-bottom: 28px;
  flex-wrap: wrap;
}

.header-left {
  flex: 1;
  min-width: 250px;
}

.page-title {
  font-size: 32px;
  font-weight: 700;
  color: #2d3748;
  margin: 0 0 8px;
  display: flex;
  align-items: center;
  gap: 12px;
}

.page-title i {
  color: #667eea;
}

.page-subtitle {
  color: #718096;
  font-size: 14px;
  margin: 0;
}

.btn-new {
  background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
  color: white;
  border: none;
  padding: 12px 24px;
  border-radius: 10px;
  font-weight: 600;
  cursor: pointer;
  transition: all 0.3s ease;
  display: flex;
  align-items: center;
  gap: 8px;
  box-shadow: 0 4px 15px rgba(102, 126, 234, 0.3);
}

.btn-new:hover {
  transform: translateY(-2px);
  box-shadow: 0 8px 25px rgba(102, 126, 234, 0.4);
}

/* Search Bar */
.search-bar {
  display: flex;
  gap: 16px;
  align-items: center;
  margin-bottom: 24px;
  flex-wrap: wrap;
}

.search-input-wrapper {
  flex: 1;
  min-width: 250px;
  position: relative;
  display: flex;
  align-items: center;
  background: white;
  border-radius: 10px;
  padding: 0 14px;
  box-shadow: 0 2px 8px rgba(0, 0, 0, 0.05);
}

.search-input-wrapper i {
  color: #a0aec0;
  margin-right: 10px;
  font-size: 16px;
}

.search-input {
  flex: 1;
  border: none;
  padding: 12px 0;
  font-size: 14px;
  background: transparent;
  outline: none;
  font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
}

.search-input::placeholder {
  color: #cbd5e0;
}

.result-count {
  background: white;
  padding: 8px 12px;
  border-radius: 8px;
  font-size: 13px;
  color: #718096;
  font-weight: 500;
  box-shadow: 0 2px 8px rgba(0, 0, 0, 0.05);
}

/* Empty State */
.empty-state {
  background: white;
  border-radius: 14px;
  padding: 60px 40px;
  text-align: center;
  box-shadow: 0 2px 12px rgba(0, 0, 0, 0.08);
}

.empty-icon {
  font-size: 64px;
  color: #cbd5e0;
  margin-bottom: 20px;
}

.empty-state h3 {
  font-size: 20px;
  color: #2d3748;
  margin-bottom: 8px;
  font-weight: 600;
}

.empty-state p {
  color: #718096;
  margin-bottom: 24px;
  font-size: 14px;
}

.btn-empty {
  background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
  color: white;
  border: none;
  padding: 12px 24px;
  border-radius: 10px;
  font-weight: 600;
  cursor: pointer;
  transition: all 0.3s ease;
  display: inline-flex;
  align-items: center;
  gap: 8px;
  box-shadow: 0 4px 15px rgba(102, 126, 234, 0.3);
}

.btn-empty:hover {
  transform: translateY(-2px);
  box-shadow: 0 8px 25px rgba(102, 126, 234, 0.4);
}

/* Table Card */
.table-card {
  background: white;
  border-radius: 14px;
  box-shadow: 0 2px 12px rgba(0, 0, 0, 0.08);
  overflow: hidden;
}

.table-wrapper {
  overflow-x: auto;
}

.empleados-table {
  width: 100%;
  border-collapse: collapse;
}

.empleados-table thead {
  background: linear-gradient(135deg, #667eea15 0%, #764ba215 100%);
  border-bottom: 2px solid #e2e8f0;
}

.empleados-table th {
  padding: 14px 16px;
  text-align: left;
  font-size: 13px;
  font-weight: 600;
  color: #4a5568;
  text-transform: uppercase;
  letter-spacing: 0.5px;
}

.empleados-table th i {
  margin-right: 6px;
  color: #667eea;
}

.table-row {
  border-bottom: 1px solid #e2e8f0;
  transition: all 0.2s ease;
}

.table-row:hover {
  background: #f7fafc;
}

.empleados-table td {
  padding: 14px 16px;
  font-size: 14px;
  color: #2d3748;
}

.col-name { width: 25%; }
.col-dni { width: 15%; }
.col-email { width: 25%; }
.col-dept { width: 20%; }
.col-actions { width: 15%; text-align: center; }

.employee-cell {
  display: flex;
  align-items: center;
  gap: 10px;
}

.employee-avatar {
  width: 40px;
  height: 40px;
  border-radius: 8px;
  background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
  color: white;
  display: flex;
  align-items: center;
  justify-content: center;
  font-weight: 600;
  font-size: 12px;
  flex-shrink: 0;
}

.employee-info {
  flex: 1;
}

.employee-name {
  display: block;
  font-weight: 600;
  color: #2d3748;
}

.badge-dni {
  background: #f0f4ff;
  color: #667eea;
  padding: 4px 10px;
  border-radius: 6px;
  font-size: 12px;
  font-weight: 600;
  font-family: 'Monaco', 'Courier New', monospace;
}

.email-text {
  color: #718096;
}

.dept-badge {
  background: #e8f6f0;
  color: #10b981;
  padding: 4px 10px;
  border-radius: 6px;
  font-size: 12px;
  font-weight: 600;
}

.btn-action {
  background: none;
  border: none;
  width: 34px;
  height: 34px;
  border-radius: 8px;
  cursor: pointer;
  transition: all 0.2s ease;
  font-size: 14px;
  display: inline-flex;
  align-items: center;
  justify-content: center;
}

.btn-edit {
  color: #f59e0b;
  background: #fef3c7;
}

.btn-edit:hover {
  background: #fcd34d;
  transform: scale(1.1);
}

.btn-delete {
  color: #ef4444;
  background: #fee2e2;
}

.btn-delete:hover {
  background: #fecaca;
  transform: scale(1.1);
}

/* Modal Styles */
.modal-overlay {
  position: fixed;
  top: 0;
  left: 0;
  right: 0;
  bottom: 0;
  background: rgba(0, 0, 0, 0.5);
  display: flex;
  align-items: center;
  justify-content: center;
  z-index: 1000;
  padding: 20px;
}

.modal-content {
  background: white;
  border-radius: 14px;
  box-shadow: 0 20px 60px rgba(0, 0, 0, 0.3);
  width: 100%;
  max-width: 500px;
  animation: slideUp 0.3s ease-out;
}

.modal-confirm {
  background: white;
  border-radius: 14px;
  box-shadow: 0 20px 60px rgba(0, 0, 0, 0.3);
  padding: 40px 30px;
  text-align: center;
  width: 100%;
  max-width: 400px;
  animation: slideUp 0.3s ease-out;
}

@keyframes slideUp {
  from {
    opacity: 0;
    transform: translateY(30px);
  }
  to {
    opacity: 1;
    transform: translateY(0);
  }
}

.modal-header {
  display: flex;
  justify-content: space-between;
  align-items: center;
  padding: 20px 24px;
  border-bottom: 1px solid #e2e8f0;
}

.modal-header h2 {
  font-size: 20px;
  font-weight: 700;
  color: #2d3748;
  margin: 0;
}

.btn-close {
  background: none;
  border: none;
  font-size: 20px;
  color: #a0aec0;
  cursor: pointer;
  padding: 0;
  width: 32px;
  height: 32px;
  display: flex;
  align-items: center;
  justify-content: center;
  border-radius: 6px;
  transition: all 0.2s ease;
}

.btn-close:hover {
  background: #f0f4f8;
  color: #2d3748;
}

.modal-form {
  padding: 24px;
}

.form-group {
  margin-bottom: 18px;
}

.form-group label {
  display: block;
  font-size: 13px;
  font-weight: 600;
  color: #2d3748;
  margin-bottom: 8px;
  text-transform: uppercase;
  letter-spacing: 0.5px;
}

.form-group input {
  width: 100%;
  padding: 10px 14px;
  border: 2px solid #e2e8f0;
  border-radius: 8px;
  font-size: 14px;
  font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
  transition: all 0.2s ease;
}

.form-group input:focus {
  outline: none;
  border-color: #667eea;
  box-shadow: 0 0 0 3px rgba(102, 126, 234, 0.1);
}

.form-group input::placeholder {
  color: #cbd5e0;
}

.modal-actions {
  display: flex;
  gap: 12px;
  margin-top: 28px;
}

.btn-cancel,
.btn-submit {
  flex: 1;
  padding: 12px 16px;
  border: none;
  border-radius: 8px;
  font-weight: 600;
  cursor: pointer;
  transition: all 0.2s ease;
  display: flex;
  align-items: center;
  justify-content: center;
  gap: 6px;
  font-size: 14px;
}

.btn-cancel {
  background: #f0f4f8;
  color: #4a5568;
}

.btn-cancel:hover {
  background: #e2e8f0;
}

.btn-submit {
  background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
  color: white;
  box-shadow: 0 4px 15px rgba(102, 126, 234, 0.3);
}

.btn-submit:hover {
  transform: translateY(-1px);
  box-shadow: 0 6px 20px rgba(102, 126, 234, 0.4);
}

/* Confirmation Modal */
.confirm-icon {
  font-size: 56px;
  color: #f59e0b;
  margin-bottom: 16px;
}

.modal-confirm h3 {
  font-size: 18px;
  color: #2d3748;
  margin-bottom: 8px;
  font-weight: 600;
}

.modal-confirm p {
  color: #718096;
  font-size: 14px;
  margin-bottom: 24px;
}

.confirm-actions {
  display: flex;
  gap: 12px;
}

.btn-delete-confirm {
  flex: 1;
  padding: 10px 16px;
  background: linear-gradient(135deg, #ef4444 0%, #dc2626 100%);
  color: white;
  border: none;
  border-radius: 8px;
  font-weight: 600;
  cursor: pointer;
  transition: all 0.2s ease;
  display: flex;
  align-items: center;
  justify-content: center;
  gap: 6px;
}

.btn-delete-confirm:hover {
  transform: translateY(-1px);
  box-shadow: 0 6px 20px rgba(239, 68, 68, 0.4);
}

/* Transitions */
.modal-enter-active, .modal-leave-active {
  transition: opacity 0.3s ease;
}

.modal-enter-from, .modal-leave-to {
  opacity: 0;
}

/* Responsive */
@media (max-width: 768px) {
  .empleados-container {
    padding: 20px 16px;
  }

  .empleados-header {
    flex-direction: column;
    align-items: stretch;
  }

  .btn-new {
    width: 100%;
    justify-content: center;
  }

  .page-title {
    font-size: 26px;
  }

  .search-bar {
    flex-direction: column;
  }

  .search-input-wrapper {
    min-width: 100%;
  }

  .result-count {
    width: 100%;
    text-align: center;
  }

  .col-name { width: 40%; }
  .col-dni { width: 20%; }
  .col-email { display: none; }
  .col-dept { display: none; }
  .col-actions { width: 20%; }

  .table-row:not(:hover) .btn-action {
    padding: 6px;
  }

  .modal-content {
    max-width: 100%;
  }

  .empty-state {
    padding: 40px 20px;
  }
}

@media (max-width: 480px) {
  .empleados-container {
    padding: 16px 12px;
  }

  .page-title {
    font-size: 22px;
  }

  .empleados-table {
    font-size: 12px;
  }

  .empleados-table th,
  .empleados-table td {
    padding: 10px 8px;
  }

  .col-name { width: 50%; }
  .col-dni { width: 30%; }
  .col-actions { width: 20%; }

  .employee-avatar {
    width: 32px;
    height: 32px;
    font-size: 11px;
  }

  .employee-cell {
    gap: 8px;
  }

  .modal-confirm {
    padding: 30px 20px;
  }
}
</style>
